# Generated by Django 4.1.7 on 2023-04-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
