# Generated by Django 4.1.7 on 2023-04-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='razorpay_payment_status',
        ),
    ]
