# Generated by Django 4.1.7 on 2023-04-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_rename_razorpay_payment_id_payment_razorpay_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
